language: java
jdk:
  - openjdk17

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/ .2/repository'
    - '$HOME/ .gradle'

script: "./gradlew clean build"

notification:
  email:
    recipients:
      - sung2687@gmail.com
